apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-telegram.fullname" . }}
  labels:
    {{- include "mautrix-telegram.labels" . | nindent 4 }}
type: Opaque
stringData:
  registration.yaml: |
    id: {{ .Values.config.appservice.id | default "telegram" | quote }}
    as_token: {{ .Values.registration.asToken | required "registration.asToken is required" | quote }}
    hs_token: {{ .Values.registration.hsToken | required "registration.hsToken is required" | quote }}
    namespaces:
      users:
        - exclusive: true
          regex: '^@telegram_.+:{{ .Values.homeserver.domain | required "homeserver.domain is required" | replace "." "\\." }}$'
        - exclusive: true
          regex: '^@{{ .Values.config.appservice.bot_username | default "telegrambot" | replace "." "\\." }}:{{ .Values.homeserver.domain | replace "." "\\." }}$'
      aliases: []
      rooms: []
    url: http://{{ include "mautrix-telegram.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}
    sender_localpart: {{ .Values.config.appservice.bot_username | default "telegrambot" | quote }}
    rate_limited: false
